# Generated by Django 4.2 on 2026-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Phoneno', models.IntegerField()),
                ('Course', models.CharField(max_length=50)),
                ('Resume', models.FileField(upload_to='resumes/')),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=150)),
            ],
        ),
    ]
