# Generated by Django 4.2 on 2026-07-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='Phoneno',
            new_name='Phone_no',
        ),
    ]
