# Generated by Django 4.2 on 2026-07-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_phoneno_student_details_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
