# Generated by Django 4.2 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_student_details_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('Duration', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=50)),
                ('Framework', models.CharField(max_length=50)),
                ('Database', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Job_description', models.CharField(max_length=120)),
                ('Location', models.CharField(max_length=50)),
                ('starts', models.DateField()),
            ],
        ),
    ]
